/**
 * Represents a normalized lead payload generated by the frontend tools.
 * This object is independent of any specific CRM implementation.
 */
export interface Lead {
  lead: {
    name: string;
    email: string;
    companyName: string;
    phone?: string;
  };
  source: {
    tool: string;
    page: string;
    channel?: string;
  };
  result: Record<string, unknown>;
  metadata: {
    submittedAt: string;
    userAgent?: string;
    referrer?: string;
    sessionId?: string;
    campaign?: string;
  };
}

/**
 * Represents the normalized response from a CRM lead submission attempt.
 */
export interface LeadSubmissionResult {
  success: boolean;
  message: string;
  leadId?: string;
}
